/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AllRec */

#ifndef _Included_AllRec
#define _Included_AllRec
#ifdef __cplusplus
extern "C" {
#endif
#undef AllRec_serialVersionUID
#define AllRec_serialVersionUID 1i64
#undef AllRec_serialVersionUID
#define AllRec_serialVersionUID 1i64
/*
 * Class:     AllRec
 * Method:    sayHi
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_AllRec_sayHi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
