/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class singrec */

#ifndef _Included_singrec
#define _Included_singrec
#ifdef __cplusplus
extern "C" {
#endif
#undef singrec_serialVersionUID
#define singrec_serialVersionUID 1i64
#undef singrec_serialVersionUID
#define singrec_serialVersionUID 1i64
/*
 * Class:     singrec
 * Method:    getrec
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_singrec_getrec
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
